// Generated by tools/img_sizes.py: pixel size of every image in public/img. Re-run after adding images.
export const IMG: Record<string, [number, number]> = {
  'img/ch06/axeman_attack_map_march1919.jpg': [665, 792],
  'img/demo/sully_jackson_1845.jpg': [1920, 2288],
  'img/maps/mitchell_1836.jpg': [3200, 2957],
};
